import { test, expect } from '@playwright/test';

test('Adding Job Title to Emplployee', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Job' }).locator('i').click();
  await page.getByRole('menuitem', { name: 'Job Titles' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
//   await page.getByRole('textbox').nth(1).click();
//   await page.getByRole('textbox').nth(1).press('CapsLock');
//   await page.getByRole('textbox').nth(1).fill('P');
//   await page.getByRole('textbox').nth(1).press('CapsLock');
//   await page.getByRole('textbox').nth(1).fill('Playwright ');
//   await page.getByRole('textbox').nth(1).press('CapsLock');
//   await page.getByRole('textbox').nth(1).fill('Playwright T');
//   await page.getByRole('textbox').nth(1).press('CapsLock');
//   await page.getByRole('textbox').nth(1).fill('');
//   await page.getByRole('textbox').nth(1).press('CapsLock');
// //   await page.getByRole('textbox').nth(1).fill('QA');
// //   await page.getByRole('textbox').nth(1).press('CapsLock');
// //   await page.getByRole('textbox').nth(1).fill('QA ');
// //   await page.getByRole('textbox').nth(1).press('CapsLock');
//   await page.getByRole('textbox').nth(1).fill('QA E');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('QA Engg API');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
//   await page.getByRole('textbox', { name: 'Type description here' }).press('CapsLock');
//   await page.getByRole('textbox', { name: 'Type description here' }).fill('T');
//   await page.getByRole('textbox', { name: 'Type description here' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Type description here' }).fill('UI Tester');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewJobTitleList');
  await expect(page.getByText('QA Engg')).toBeVisible();
  await page.locator('span').filter({ hasText: 'Haruna Fathin' }).click();
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await expect(page.getByRole('heading', { name: 'Login' })).toBeVisible();
});